[package]
name = "amateur-radio-cmap-core"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
image = "0.25.9"
imageproc = "0.25.0"
libm = "0.2.15"
rayon = "1.11.0"
shapefile = "0.7.0"
wide = "1.0.2"
